Name:           ros-jade-gazebo-plugins
Version:        2.5.0
Release:        1%{?dist}
Summary:        ROS gazebo_plugins package

Group:          Development/Libraries
License:        BSD, Apache 2.0
URL:            http://gazebosim.org/tutorials?cat=connect_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       gazebo
Requires:       ros-jade-angles
Requires:       ros-jade-camera-info-manager
Requires:       ros-jade-cv-bridge
Requires:       ros-jade-driver-base
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-gazebo-msgs
Requires:       ros-jade-gazebo-ros
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-image-transport
Requires:       ros-jade-message-generation
Requires:       ros-jade-nav-msgs
Requires:       ros-jade-nodelet
Requires:       ros-jade-polled-camera
Requires:       ros-jade-rosconsole
Requires:       ros-jade-roscpp
Requires:       ros-jade-rosgraph-msgs
Requires:       ros-jade-rospy
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-std-srvs
Requires:       ros-jade-tf
Requires:       ros-jade-tf2-ros
Requires:       ros-jade-trajectory-msgs
Requires:       ros-jade-urdf
BuildRequires:  gazebo-devel
BuildRequires:  ros-jade-angles
BuildRequires:  ros-jade-camera-info-manager
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cv-bridge
BuildRequires:  ros-jade-diagnostic-updater
BuildRequires:  ros-jade-driver-base
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-gazebo-msgs
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-image-transport
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-nav-msgs
BuildRequires:  ros-jade-nodelet
BuildRequires:  ros-jade-polled-camera
BuildRequires:  ros-jade-rosconsole
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rosgraph-msgs
BuildRequires:  ros-jade-rospy
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-std-srvs
BuildRequires:  ros-jade-tf
BuildRequires:  ros-jade-tf2-ros
BuildRequires:  ros-jade-trajectory-msgs
BuildRequires:  ros-jade-urdf

%description
Robot-independent Gazebo plugins for sensors, motors and dynamic reconfigurable
components.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Sun Aug 16 2015 John Hsu <hsu@osrfoundation.org> - 2.5.0-1
- Autogenerated by Bloom

